- hosts: web
  tasks:
    - name: Install collectd
      apt: pkg=collectd state=present update_cache=true

    - name: Render and upload collectd.conf file
      vars:
          graphite_host: graphite
          graphite_port: 2003
          collectd_query_interval: 10
      template:
          src=./collectd.conf.j2
          dest=/etc/collectd/collectd.conf

    - name: Restart collectd
      service:
          name: collectd
          state: restarted
          enabled: true
